/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.UsuarioDAO;
import ObjetosNegocio.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Citlali Orduño
 */
public class PerfilUsuario extends javax.swing.JFrame {

    private UsuarioDAO udao;
    private Usuario usuario;
    private List<String> generosMusicales;
    private List<String> generosPeliculas;
    
    
    public PerfilUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.usuario= usuario;
        this.udao=  new UsuarioDAO();
        this.generosMusicales= new ArrayList<>();
        this.generosPeliculas=new ArrayList<>();
        this.cargarInfoPersonal();
        this.cargarComboMusica();
        this.cargarComboPeliculas();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        lblFacebbot = new javax.swing.JLabel();
        panelInformacionPersonal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        panelGustos = new javax.swing.JPanel();
        txtGustosMusicales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarMusica = new javax.swing.JButton();
        btnEliminarPeliculas = new javax.swing.JButton();
        txtGenerosPeliculas = new javax.swing.JTextField();
        cmbGenerosPeliculas = new javax.swing.JComboBox<>();
        cmbGenerosMusicales = new javax.swing.JComboBox<>();
        btnAgregarPeliculas1 = new javax.swing.JButton();
        btnEliminarMusica = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(51, 51, 255));

        lblFacebbot.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblFacebbot.setText("Faceboot");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(lblFacebbot, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblFacebbot)
                .addGap(19, 19, 19))
        );

        panelInformacionPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Información personal"));

        jLabel1.setText("Nombre: ");

        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout panelInformacionPersonalLayout = new javax.swing.GroupLayout(panelInformacionPersonal);
        panelInformacionPersonal.setLayout(panelInformacionPersonalLayout);
        panelInformacionPersonalLayout.setHorizontalGroup(
            panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionPersonalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(txtContrasenia))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelInformacionPersonalLayout.setVerticalGroup(
            panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionPersonalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGustos.setBorder(javax.swing.BorderFactory.createTitledBorder("Gustos personales"));

        jLabel5.setText("Agrega o elimina tus gustos musicales.");

        btnAgregarMusica.setText("Agregar");
        btnAgregarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMusicaActionPerformed(evt);
            }
        });

        btnEliminarPeliculas.setText("Eliminar");
        btnEliminarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliculasActionPerformed(evt);
            }
        });

        cmbGenerosPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbGenerosMusicales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarPeliculas1.setText("Agregar");
        btnAgregarPeliculas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculas1ActionPerformed(evt);
            }
        });

        btnEliminarMusica.setText("Eliminar");
        btnEliminarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMusicaActionPerformed(evt);
            }
        });

        jLabel6.setText("Agrega o elimina tus gustos de generos de películas.");

        javax.swing.GroupLayout panelGustosLayout = new javax.swing.GroupLayout(panelGustos);
        panelGustos.setLayout(panelGustosLayout);
        panelGustosLayout.setHorizontalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGustosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(panelGustosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGustosLayout.createSequentialGroup()
                        .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGustosLayout.createSequentialGroup()
                                .addComponent(cmbGenerosMusicales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarMusica))
                            .addGroup(panelGustosLayout.createSequentialGroup()
                                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGenerosPeliculas)
                                    .addComponent(cmbGenerosPeliculas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGustosMusicales))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarMusica)
                                    .addComponent(btnEliminarPeliculas)
                                    .addComponent(btnAgregarPeliculas1))))
                        .addGap(17, 17, 17))))
        );
        panelGustosLayout.setVerticalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGustosMusicales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMusica))
                .addGap(18, 18, 18)
                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMusica)
                    .addComponent(cmbGenerosMusicales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenerosPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPeliculas1))
                .addGap(18, 18, 18)
                .addGroup(panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGenerosPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPeliculas))
                .addGap(25, 25, 25))
        );

        jLabel4.setText("En esta sección, podrás modificar tu información personal.");

        btnInicio.setText("Volver al inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarCambios)
                        .addGap(18, 18, 18)
                        .addComponent(btnInicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelInformacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addComponent(panelGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGustos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInformacionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(btnGuardarCambios))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPeliculasActionPerformed

    private void btnEliminarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMusicaActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        MuroPosts muroPosts = new MuroPosts();
        muroPosts.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnAgregarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMusicaActionPerformed

    private void btnAgregarPeliculas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPeliculas1ActionPerformed

    
    public void cargarInfoPersonal(){
        txtNombre.setText(usuario.getNombre());
        txtContrasenia.setText(usuario.getContraseña());
    }
    
    public void cargarComboMusica(){
        cmbGenerosPeliculas.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<String> generos = udao.mostrarGenerosMusicales(usuario);
        for (String genero : generos) {
            model.addElement(genero);
        }
        this.cmbGenerosMusicales.setModel(model);
    }
    
    public void cargarComboPeliculas(){
        cmbGenerosPeliculas.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<String> peliculas = udao.mostrarGenerosPeliculas(usuario);
        for (String pelicula : peliculas) {
            model.addElement(peliculas);
        }
        this.cmbGenerosPeliculas.setModel(model);
    }
    
    
    public void eliminarGenerosMusicales(){
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMusica;
    private javax.swing.JButton btnAgregarPeliculas1;
    private javax.swing.JButton btnEliminarMusica;
    private javax.swing.JButton btnEliminarPeliculas;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<String> cmbGenerosMusicales;
    private javax.swing.JComboBox<String> cmbGenerosPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFacebbot;
    private javax.swing.JPanel panelGustos;
    private javax.swing.JPanel panelInformacionPersonal;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtGenerosPeliculas;
    private javax.swing.JTextField txtGustosMusicales;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
